######################################################################
# Automatically generated by qmake (2.01a) Thu Apr 4 22:14:02 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp RectPacker.cpp
HEADERS += RectPacker.h
